packages:
  wmbus-gateway: github://IoTLabs-pl/wM-Bus-Gateway/packages/wmbus_gateway.yaml@v1.0.3

esphome:
  name: supla-wmbus
  min_version: 2025.7.0
  project:
    version: v1.0.0-supla

esp32:
  framework:
    advanced:
      enable_lwip_dhcp_server: true
    sdkconfig_options:
      CONFIG_HTTPD_MAX_REQ_HDR_LEN: "1024"
      CONFIG_SUPLA_DEBUG_BUILD: "y"
      CONFIG_ESP_TLS_USING_MBEDTLS: "y"
      CONFIG_ESP_TLS_INSECURE: "y"
      CONFIG_ESP_TLS_SKIP_SERVER_CERT_VERIFY: "y"

mdns:
  disabled: True

wmbus_radio:
  on_frame:
    then:
      - logger.log:
          level: WARN
          format: "Meter ID: %s"
          args: ["frame->meter_id().c_str()"]
      - logger.log:
          level: WARN
          format: "Frame: https://wmbusmeters.org/analyze/%s"
          args: ["frame->as_hex().c_str()"]

wmbus_common:
  drivers: all

supla_device:
  version: v25.6

supla_wmbus:

script:
  - id: blinker_script
    then:
      - repeat:
          count: 20
          then:
            - light.control:
                id: wmbus_gateway_status_led
                state: !lambda return iteration % 2 == 0;
            - delay: 50ms

image:
  - id: !extend qr_code
    file: resources/qrcode.png

binary_sensor:
  - id: !extend ext_button
    on_multi_click:
      - timing:
          - ON for at least 5s
        then:
          - lambda: SuplaDevice.enterConfigMode();
      - timing:
          - ON for at least 12s
        then:
          - lambda: |-
              SuplaDevice.resetToFactorySettings();
              SuplaDevice.softRestart();
