packages:
  core: !include
    file: /home/kuba/wmbus/wM-Bus-Gateway/packages/wmbus_gateway_core.yaml

esphome:
  name: supla-wmbus

esp32:
  framework:
    sdkconfig_options:
      CONFIG_HTTPD_MAX_REQ_HDR_LEN: "1024"
      CONFIG_SUPLA_DEBUG_BUILD: "y"
      CONFIG_LOG_MAXIMUM_LEVEL: CONFIG_LOG_MAXIMUM_LEVEL_DEBUG
      CONFIG_LOG_DEFAULT_LEVEL: CONFIG_LOG_DEFAULT_LEVEL_DEBUG
      CONFIG_ESP_TLS_USING_MBEDTLS: "y"
      CONFIG_ESP_TLS_INSECURE: "y"
      CONFIG_ESP_TLS_SKIP_SERVER_CERT_VERIFY: "y"

mdns:
  disabled: True

wmbus_radio:
  on_frame:
    - then:
        - logger.log:
            level: WARN
            format: "Meter ID: %s"
            args: ["frame->meter_id().c_str()"]
        - logger.log:
            level: WARN
            format: "Frame: https://wmbusmeters.org/analyze/%s"
            args: ["frame->as_hex().c_str()"]

wmbus_common:
  drivers: all

wmbus_meter:

supla_wmbus:

image:
  - id: !remove qr_code
  - id: qr_code
    file: resources/qrcode.png
    type: binary
    invert_alpha: True

binary_sensor:
  - id: !extend ext_button
    on_multi_click:
      - timing:
          - ON for at least 5s
        then:
          - lambda: SuplaDevice.enterConfigMode();
      - timing:
          - ON for at least 12s
        then:
          - lambda: |-
              SuplaDevice.resetToFactorySettings();
              SuplaDevice.softRestart();
