name: Build and store firmware
on: 
    pull_request:
    release:
      types:
        - published
jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build firmware
        id: build_firmware
        uses: esphome/build-action@v7
        with:
          yaml-file: wmbus-gateway.yaml
          complete-manifest: true
      - name: Upload binaries to release
        if: ${{ github.event_name == 'release' }}
        uses: softprops/action-gh-release@v2
        with:
          files: ${{steps.build_firmware.outputs.name}}/*.{bin,json}
                 

