name: Build release firmware
on:
  release:
    types:
      - published
jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build firmware
        id: build_firmware
        uses: esphome/build-action@v7
        with:
          yaml-file: wmbus_gateway.yaml
          complete-manifest: true
      - name: Alter `new_install_prompt_erase` manifest field
        env: 
          BAK_FILE: "${{ steps.build_firmware.outputs.name }}/manifest.json.bak"
          FILE: "${{ steps.build_firmware.outputs.name }}/manifest.json"
        run: |
          mv "$FILE" "$BAK_FILE"
          jq '.new_install_prompt_erase = true' "$BAK_FILE" > "$FILE"
      - name: Upload binaries to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ steps.build_firmware.outputs.name }}/*.factory.bin
            ${{ steps.build_firmware.outputs.name }}/manifest.json
